version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
    timezone: Europe/Prague
  open-pull-requests-limit: 10
  reviewers:
  - AuHau
  ignore:
  - dependency-name: truffle
    versions:
    - 5.1.63
    - 5.1.64
    - 5.1.65
    - 5.1.66
    - 5.1.67
    - 5.2.1
    - 5.2.2
    - 5.2.5
    - 5.2.6
    - 5.3.0
    - 5.3.1
  - dependency-name: prettier-plugin-solidity
    versions:
    - 1.0.0-beta.7
    - 1.0.0-beta.8
  - dependency-name: "@truffle/hdwallet-provider"
    versions:
    - 1.2.4
    - 1.2.6
  - dependency-name: "@openzeppelin/truffle-upgrades"
    versions:
    - 1.4.0
    - 1.5.0
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: "@openzeppelin/contracts"
    versions:
    - 3.4.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
  - dependency-name: web3-utils
    versions:
    - 1.3.3
