/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface PinningManagerInterface extends Interface {
  functions: {
    offerRegistry: TypedFunctionDescription<{ encode([]: [string]): string }>;

    setStorageOffer: TypedFunctionDescription<{
      encode([capacity, maximumDuration, periods, pricesForPeriods, message]: [
        BigNumberish,
        BigNumberish,
        BigNumberish[],
        BigNumberish[],
        Arrayish[]
      ]): string;
    }>;

    increaseStorageCapacity: TypedFunctionDescription<{
      encode([increase]: [BigNumberish]): string;
    }>;

    decreaseStorageCapacity: TypedFunctionDescription<{
      encode([decrease]: [BigNumberish]): string;
    }>;

    stopStorage: TypedFunctionDescription<{ encode([]: []): string }>;

    setStoragePrice: TypedFunctionDescription<{
      encode([periods, pricesForPeriods]: [
        BigNumberish[],
        BigNumberish[]
      ]): string;
    }>;

    setMaximumDuration: TypedFunctionDescription<{
      encode([maximumDuration]: [BigNumberish]): string;
    }>;

    emitMessage: TypedFunctionDescription<{
      encode([message]: [Arrayish[]]): string;
    }>;

    newRequest: TypedFunctionDescription<{
      encode([fileReference, provider, size, period]: [
        Arrayish[],
        string,
        BigNumberish,
        BigNumberish
      ]): string;
    }>;

    topUpRequest: TypedFunctionDescription<{
      encode([fileReference, provider]: [Arrayish[], string]): string;
    }>;

    stopRequestDuring: TypedFunctionDescription<{
      encode([fileReference, provider]: [Arrayish[], string]): string;
    }>;

    withdrawEarnings: TypedFunctionDescription<{
      encode([requestReferences]: [Arrayish[]]): string;
    }>;

    getRequestReference: TypedFunctionDescription<{
      encode([fileReference]: [Arrayish[]]): string;
    }>;
  };

  events: {
    CapacitySet: TypedEventDescription<{
      encodeTopics([storer, capacity]: [string | null, null]): string[];
    }>;

    EarningsWithdrawn: TypedEventDescription<{
      encodeTopics([requestReference]: [Arrayish | null]): string[];
    }>;

    MaximumDurationSet: TypedEventDescription<{
      encodeTopics([storer, maximumDuration]: [string | null, null]): string[];
    }>;

    MessageEmitted: TypedEventDescription<{
      encodeTopics([storer, message]: [string | null, null]): string[];
    }>;

    PriceSet: TypedEventDescription<{
      encodeTopics([storer, period, price]: [
        string | null,
        null,
        null
      ]): string[];
    }>;

    RequestMade: TypedEventDescription<{
      encodeTopics([
        requestReference,
        fileReference,
        requester,
        provider,
        size,
        period,
        deposited
      ]: [
        null,
        Arrayish[] | null,
        string | null,
        string | null,
        null,
        null,
        null
      ]): string[];
    }>;

    RequestStopped: TypedEventDescription<{
      encodeTopics([requestReference]: [Arrayish | null]): string[];
    }>;

    RequestTopUp: TypedEventDescription<{
      encodeTopics([requestReference, deposited]: [
        Arrayish | null,
        null
      ]): string[];
    }>;
  };
}

export class PinningManager extends Contract {
  connect(signerOrProvider: Signer | Provider | string): PinningManager;
  attach(addressOrName: string): PinningManager;
  deployed(): Promise<PinningManager>;

  on(event: EventFilter | string, listener: Listener): PinningManager;
  once(event: EventFilter | string, listener: Listener): PinningManager;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): PinningManager;
  removeAllListeners(eventName: EventFilter | string): PinningManager;
  removeListener(eventName: any, listener: Listener): PinningManager;

  interface: PinningManagerInterface;

  functions: {
    offerRegistry(
      arg0: string
    ): Promise<{
      capacity: BigNumber;
      maximumDuration: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;

    setStorageOffer(
      capacity: BigNumberish,
      maximumDuration: BigNumberish,
      periods: BigNumberish[],
      pricesForPeriods: BigNumberish[],
      message: Arrayish[],
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    increaseStorageCapacity(
      increase: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    decreaseStorageCapacity(
      decrease: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    stopStorage(overrides?: TransactionOverrides): Promise<ContractTransaction>;

    setStoragePrice(
      periods: BigNumberish[],
      pricesForPeriods: BigNumberish[],
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    setMaximumDuration(
      maximumDuration: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    emitMessage(
      message: Arrayish[],
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    newRequest(
      fileReference: Arrayish[],
      provider: string,
      size: BigNumberish,
      period: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    topUpRequest(
      fileReference: Arrayish[],
      provider: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    stopRequestDuring(
      fileReference: Arrayish[],
      provider: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    withdrawEarnings(
      requestReferences: Arrayish[],
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    getRequestReference(fileReference: Arrayish[]): Promise<string>;
  };

  offerRegistry(
    arg0: string
  ): Promise<{
    capacity: BigNumber;
    maximumDuration: BigNumber;
    0: BigNumber;
    1: BigNumber;
  }>;

  setStorageOffer(
    capacity: BigNumberish,
    maximumDuration: BigNumberish,
    periods: BigNumberish[],
    pricesForPeriods: BigNumberish[],
    message: Arrayish[],
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  increaseStorageCapacity(
    increase: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  decreaseStorageCapacity(
    decrease: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  stopStorage(overrides?: TransactionOverrides): Promise<ContractTransaction>;

  setStoragePrice(
    periods: BigNumberish[],
    pricesForPeriods: BigNumberish[],
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  setMaximumDuration(
    maximumDuration: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  emitMessage(
    message: Arrayish[],
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  newRequest(
    fileReference: Arrayish[],
    provider: string,
    size: BigNumberish,
    period: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  topUpRequest(
    fileReference: Arrayish[],
    provider: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  stopRequestDuring(
    fileReference: Arrayish[],
    provider: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  withdrawEarnings(
    requestReferences: Arrayish[],
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  getRequestReference(fileReference: Arrayish[]): Promise<string>;

  filters: {
    CapacitySet(storer: string | null, capacity: null): EventFilter;

    EarningsWithdrawn(requestReference: Arrayish | null): EventFilter;

    MaximumDurationSet(
      storer: string | null,
      maximumDuration: null
    ): EventFilter;

    MessageEmitted(storer: string | null, message: null): EventFilter;

    PriceSet(storer: string | null, period: null, price: null): EventFilter;

    RequestMade(
      requestReference: null,
      fileReference: Arrayish[] | null,
      requester: string | null,
      provider: string | null,
      size: null,
      period: null,
      deposited: null
    ): EventFilter;

    RequestStopped(requestReference: Arrayish | null): EventFilter;

    RequestTopUp(
      requestReference: Arrayish | null,
      deposited: null
    ): EventFilter;
  };

  estimate: {
    offerRegistry(arg0: string): Promise<BigNumber>;

    setStorageOffer(
      capacity: BigNumberish,
      maximumDuration: BigNumberish,
      periods: BigNumberish[],
      pricesForPeriods: BigNumberish[],
      message: Arrayish[]
    ): Promise<BigNumber>;

    increaseStorageCapacity(increase: BigNumberish): Promise<BigNumber>;

    decreaseStorageCapacity(decrease: BigNumberish): Promise<BigNumber>;

    stopStorage(): Promise<BigNumber>;

    setStoragePrice(
      periods: BigNumberish[],
      pricesForPeriods: BigNumberish[]
    ): Promise<BigNumber>;

    setMaximumDuration(maximumDuration: BigNumberish): Promise<BigNumber>;

    emitMessage(message: Arrayish[]): Promise<BigNumber>;

    newRequest(
      fileReference: Arrayish[],
      provider: string,
      size: BigNumberish,
      period: BigNumberish
    ): Promise<BigNumber>;

    topUpRequest(
      fileReference: Arrayish[],
      provider: string
    ): Promise<BigNumber>;

    stopRequestDuring(
      fileReference: Arrayish[],
      provider: string
    ): Promise<BigNumber>;

    withdrawEarnings(requestReferences: Arrayish[]): Promise<BigNumber>;

    getRequestReference(fileReference: Arrayish[]): Promise<BigNumber>;
  };
}
